#!/bin/bash
FILE=memoria
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --show-possibly-lost=no --show-reachable=no --num-callers=20 --log-file="valgrind.log" ./$FILE
fi